<?php
// This file is part of Moodle - http://moodle.org/

defined('MOODLE_INTERNAL') || die();

$functions = [
    'mod_seminarplaner_get_method_cards' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_method_cards',
        'description' => 'Get seminar units for current user/activity.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_save_method_cards' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'save_method_cards',
        'description' => 'Save seminar units for current user/activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_list_global_methodsets' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'list_global_methodsets',
        'description' => 'List published global method sets from local_seminarplaner.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_import_global_methodset' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'import_global_methodset',
        'description' => 'Import a global method set into the current activity seminar units.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_get_methodset_sync_status' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_methodset_sync_status',
        'description' => 'Get method-set sync status for the activity.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_set_methodset_sync_policy' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'set_methodset_sync_policy',
        'description' => 'Set auto-update policy for one linked method set in the activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_apply_methodset_updates' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'apply_methodset_updates',
        'description' => 'Apply pending/global updates for one linked method set in the activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_list_review_targets' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'list_review_targets',
        'description' => 'List global method sets that can be updated and resubmitted for review.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_list_reviewer_candidates' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'list_reviewer_candidates',
        'description' => 'List users that can review global method sets in the current scope.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_get_review_method_candidates' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_review_method_candidates',
        'description' => 'List new/changed activity methods against a selected global method set.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_submit_methodset_for_review' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'submit_methodset_for_review',
        'description' => 'Create/update a global method set from the activity and submit it for review.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_create_methodset_for_review' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'create_methodset_for_review',
        'description' => 'Create a new global method set from selected activity methods and submit it for review.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_create_grid' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'create_grid',
        'description' => 'Create a seminar plan in a Seminarplaner activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_list_grids' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'list_grids',
        'description' => 'List seminar plans in a Seminarplaner activity.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_get_roterfaden_state' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_roterfaden_state',
        'description' => 'Read published Common Thread state for an activity.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_publish_roterfaden' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'publish_roterfaden',
        'description' => 'Publish one seminar plan snapshot as Common Thread.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_unpublish_roterfaden' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'unpublish_roterfaden',
        'description' => 'Set Common Thread snapshot to not visible.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_delete_grid' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'delete_grid',
        'description' => 'Archive (delete) a seminar plan in a Seminarplaner activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_get_user_state' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_user_state',
        'description' => 'Get user state for a seminar plan.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_save_user_state' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'save_user_state',
        'description' => 'Save user state for a seminar plan.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_get_planning_state' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'get_planning_state',
        'description' => 'Get shared planning mode state for activity.',
        'type' => 'read',
        'ajax' => true,
    ],
    'mod_seminarplaner_save_planning_state' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'save_planning_state',
        'description' => 'Save shared planning mode state for activity.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_validate_import_payload' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'validate_import_payload',
        'description' => 'Validate a legacy import payload.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_validate_export_payload' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'validate_export_payload',
        'description' => 'Validate a legacy export payload.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_acquire_lock' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'acquire_lock',
        'description' => 'Acquire a soft lock for a seminar plan.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_refresh_lock' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'refresh_lock',
        'description' => 'Refresh a soft lock for a seminar plan.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_release_lock' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'release_lock',
        'description' => 'Release a soft lock for a seminar plan.',
        'type' => 'write',
        'ajax' => true,
    ],
    'mod_seminarplaner_lock_status' => [
        'classname' => 'mod_seminarplaner\\external\\api',
        'methodname' => 'lock_status',
        'description' => 'Get lock status for a seminar plan.',
        'type' => 'read',
        'ajax' => true,
    ],
];
